package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"time"

	"github.com/tuankhanhvo/pulseops/graph/generated"
	"github.com/tuankhanhvo/pulseops/graph/model"
)

// AcknowledgeIncident is the resolver for the acknowledgeIncident field.
func (r *mutationResolver) AcknowledgeIncident(ctx context.Context, id string, message *string) (*model.Incident, error) {
	// TODO: implement.
	return nil, nil
}

// InvestigateIncident is the resolver for the investigateIncident field.
func (r *mutationResolver) InvestigateIncident(ctx context.Context, id string, message *string) (*model.Incident, error) {
	// TODO: implement.
	return nil, nil
}

// ResolveIncident is the resolver for the resolveIncident field.
func (r *mutationResolver) ResolveIncident(ctx context.Context, id string, summary *string) (*model.Incident, error) {
	// TODO: implement.
	return nil, nil
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, name string) (*model.Team, error) {
	// TODO: implement.
	return nil, nil
}

// InviteMember is the resolver for the inviteMember field.
func (r *mutationResolver) InviteMember(ctx context.Context, teamID string, email string, role model.Role) (*model.User, error) {
	// TODO: implement.
	return nil, nil
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, teamID string, userID string) (bool, error) {
	// TODO: implement.
	return false, nil
}

// UpdateSchedule is the resolver for the updateSchedule field.
func (r *mutationResolver) UpdateSchedule(ctx context.Context, teamID string, rotation []string, intervalDays int) (*model.OnCallSchedule, error) {
	// TODO: implement.
	return nil, nil
}

// AddOverride is the resolver for the addOverride field.
func (r *mutationResolver) AddOverride(ctx context.Context, teamID string, userID string, startsAt time.Time, endsAt time.Time, reason string) (*model.ScheduleOverride, error) {
	// TODO: implement.
	return nil, nil
}

// UpsertRunbook is the resolver for the upsertRunbook field.
func (r *mutationResolver) UpsertRunbook(ctx context.Context, id *string, teamID string, title string, content string, tags []string) (*model.Runbook, error) {
	// TODO: implement.
	return nil, nil
}

// CreatePostmortem is the resolver for the createPostmortem field.
func (r *mutationResolver) CreatePostmortem(ctx context.Context, incidentID string, summary string, timeline string, actionItems []string) (*model.Postmortem, error) {
	// TODO: implement.
	return nil, nil
}

// RotateAPIKey is the resolver for the rotateApiKey field.
func (r *mutationResolver) RotateAPIKey(ctx context.Context, teamID string) (string, error) {
	// TODO: implement.
	return "", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// TODO: implement.
	return nil, nil
}

// Incidents is the resolver for the incidents field.
func (r *queryResolver) Incidents(ctx context.Context, teamID *string, status *model.IncidentStatus, severity *model.Severity, from *time.Time, to *time.Time, limit *int, offset *int) (*model.IncidentPage, error) {
	// TODO: implement.
	return nil, nil
}

// Incident is the resolver for the incident field.
func (r *queryResolver) Incident(ctx context.Context, id string) (*model.Incident, error) {
	// TODO: implement.
	return nil, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	// TODO: implement.
	return nil, nil
}

// Analytics is the resolver for the analytics field.
func (r *queryResolver) Analytics(ctx context.Context, teamID *string, from *time.Time, to *time.Time) (*model.Analytics, error) {
	// TODO: implement.
	return nil, nil
}

// Runbooks is the resolver for the runbooks field.
func (r *queryResolver) Runbooks(ctx context.Context, teamID *string, query *string) ([]*model.Runbook, error) {
	// TODO: implement.
	return nil, nil
}

// IncidentFeed is the resolver for the incidentFeed field.
func (r *subscriptionResolver) IncidentFeed(ctx context.Context, teamID string, severity *model.Severity, status *model.IncidentStatus) (<-chan *model.IncidentEvent, error) {
	// TODO: implement.
	return nil, nil
}

// OnCallStatus is the resolver for the onCallStatus field.
func (r *subscriptionResolver) OnCallStatus(ctx context.Context, teamID string) (<-chan *model.OnCallStatusEvent, error) {
	// TODO: implement.
	return nil, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
