// Code generated by gqlgen. DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Alert struct {
	ID          string                 `json:"id"`
	IncidentID  string                 `json:"incidentId"`
	Source      string                 `json:"source"`
	AlertName   string                 `json:"alertName"`
	Severity    Severity               `json:"severity"`
	Environment string                 `json:"environment"`
	Payload     map[string]interface{} `json:"payload"`
	Fingerprint string                 `json:"fingerprint"`
	ReceivedAt  time.Time              `json:"receivedAt"`
}

type Analytics struct {
	MttrSeconds int             `json:"mttrSeconds"`
	MttaSeconds int             `json:"mttaSeconds"`
	TotalCount  int             `json:"totalCount"`
	ByDay       []*DayStat      `json:"byDay"`
	BySeverity  []*SeverityStat `json:"bySeverity"`
}

type DayStat struct {
	Date  time.Time `json:"date"`
	Count int       `json:"count"`
}

type EscalationPolicy struct {
	ID     string            `json:"id"`
	TeamID string            `json:"teamId"`
	Tiers  []*EscalationTier `json:"tiers"`
}

type EscalationTier struct {
	TierNumber   int    `json:"tierNumber"`
	WaitMinutes  int    `json:"waitMinutes"`
	NotifyUserID string `json:"notifyUserId"`
	NotifyUser   *User  `json:"notifyUser"`
}

type Incident struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Status         IncidentStatus `json:"status"`
	Severity       Severity       `json:"severity"`
	TeamID         string         `json:"teamId"`
	Fingerprint    string         `json:"fingerprint"`
	AlertCount     int            `json:"alertCount"`
	TriggeredAt    time.Time      `json:"triggeredAt"`
	AcknowledgedAt *time.Time     `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy *User          `json:"acknowledgedBy,omitempty"`
	ResolvedAt     *time.Time     `json:"resolvedAt,omitempty"`
	ResolvedBy     *User          `json:"resolvedBy,omitempty"`
	Escalated      bool           `json:"escalated"`
	EscalatedAt    *time.Time     `json:"escalatedAt,omitempty"`
	Assignee       *User          `json:"assignee,omitempty"`
	Runbook        *Runbook       `json:"runbook,omitempty"`
	StatusMessage  *string        `json:"statusMessage,omitempty"`
	Mttr           *int           `json:"mttr,omitempty"`
	Alerts         []*Alert       `json:"alerts"`
}

type IncidentEvent struct {
	Type       IncidentEventType `json:"type"`
	Incident   *Incident         `json:"incident"`
	Actor      *User             `json:"actor,omitempty"`
	OccurredAt time.Time         `json:"occurredAt"`
}

type IncidentPage struct {
	Items      []*Incident `json:"items"`
	TotalCount int         `json:"totalCount"`
	HasMore    bool        `json:"hasMore"`
}

type Mutation struct {
}

type OnCallSchedule struct {
	ID            string              `json:"id"`
	TeamID        string              `json:"teamId"`
	Rotation      []*User             `json:"rotation"`
	IntervalDays  int                 `json:"intervalDays"`
	CycleStart    time.Time           `json:"cycleStart"`
	CurrentOnCall *User               `json:"currentOnCall"`
	Overrides     []*ScheduleOverride `json:"overrides"`
}

type OnCallStatusEvent struct {
	TeamID        string    `json:"teamId"`
	CurrentOnCall *User     `json:"currentOnCall"`
	NextOnCall    *User     `json:"nextOnCall"`
	HandoffAt     time.Time `json:"handoffAt"`
}

type Postmortem struct {
	ID          string    `json:"id"`
	IncidentID  string    `json:"incidentId"`
	AuthorID    string    `json:"authorId"`
	Summary     string    `json:"summary"`
	Timeline    string    `json:"timeline"`
	ActionItems []string  `json:"actionItems"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Query struct {
}

type Runbook struct {
	ID        string    `json:"id"`
	TeamID    string    `json:"teamId"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Tags      []string  `json:"tags"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ScheduleOverride struct {
	ID       string    `json:"id"`
	User     *User     `json:"user"`
	StartsAt time.Time `json:"startsAt"`
	EndsAt   time.Time `json:"endsAt"`
	Reason   string    `json:"reason"`
}

type SeverityStat struct {
	Severity Severity `json:"severity"`
	Count    int      `json:"count"`
}

type Subscription struct {
}

type Team struct {
	ID               string            `json:"id"`
	Name             string            `json:"name"`
	Members          []*User           `json:"members"`
	OnCallSchedule   *OnCallSchedule   `json:"onCallSchedule,omitempty"`
	EscalationPolicy *EscalationPolicy `json:"escalationPolicy,omitempty"`
	APIKeyHint       *string           `json:"apiKeyHint,omitempty"`
}

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Name          string    `json:"name"`
	AvatarURL     *string   `json:"avatarUrl,omitempty"`
	TeamID        string    `json:"teamId"`
	Role          Role      `json:"role"`
	GoogleSubject string    `json:"googleSubject"`
	CreatedAt     time.Time `json:"createdAt"`
}

type IncidentEventType string

const (
	IncidentEventTypeIncidentCreated       IncidentEventType = "INCIDENT_CREATED"
	IncidentEventTypeIncidentAcknowledged  IncidentEventType = "INCIDENT_ACKNOWLEDGED"
	IncidentEventTypeIncidentInvestigating IncidentEventType = "INCIDENT_INVESTIGATING"
	IncidentEventTypeIncidentResolved      IncidentEventType = "INCIDENT_RESOLVED"
	IncidentEventTypeIncidentEscalated     IncidentEventType = "INCIDENT_ESCALATED"
	IncidentEventTypeAlertAttached         IncidentEventType = "ALERT_ATTACHED"
)

var AllIncidentEventType = []IncidentEventType{
	IncidentEventTypeIncidentCreated,
	IncidentEventTypeIncidentAcknowledged,
	IncidentEventTypeIncidentInvestigating,
	IncidentEventTypeIncidentResolved,
	IncidentEventTypeIncidentEscalated,
	IncidentEventTypeAlertAttached,
}

func (e IncidentEventType) IsValid() bool {
	switch e {
	case IncidentEventTypeIncidentCreated, IncidentEventTypeIncidentAcknowledged, IncidentEventTypeIncidentInvestigating, IncidentEventTypeIncidentResolved, IncidentEventTypeIncidentEscalated, IncidentEventTypeAlertAttached:
		return true
	}
	return false
}

func (e IncidentEventType) String() string {
	return string(e)
}

func (e *IncidentEventType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncidentEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncidentEventType", str)
	}
	return nil
}

func (e IncidentEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type IncidentStatus string

const (
	IncidentStatusTriggered     IncidentStatus = "TRIGGERED"
	IncidentStatusAcknowledged  IncidentStatus = "ACKNOWLEDGED"
	IncidentStatusInvestigating IncidentStatus = "INVESTIGATING"
	IncidentStatusResolved      IncidentStatus = "RESOLVED"
	IncidentStatusClosed        IncidentStatus = "CLOSED"
)

var AllIncidentStatus = []IncidentStatus{
	IncidentStatusTriggered,
	IncidentStatusAcknowledged,
	IncidentStatusInvestigating,
	IncidentStatusResolved,
	IncidentStatusClosed,
}

func (e IncidentStatus) IsValid() bool {
	switch e {
	case IncidentStatusTriggered, IncidentStatusAcknowledged, IncidentStatusInvestigating, IncidentStatusResolved, IncidentStatusClosed:
		return true
	}
	return false
}

func (e IncidentStatus) String() string {
	return string(e)
}

func (e *IncidentStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncidentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncidentStatus", str)
	}
	return nil
}

func (e IncidentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleOwner     Role = "OWNER"
	RoleResponder Role = "RESPONDER"
	RoleViewer    Role = "VIEWER"
)

var AllRole = []Role{
	RoleOwner,
	RoleResponder,
	RoleViewer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleOwner, RoleResponder, RoleViewer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Severity string

const (
	SeverityCritical Severity = "CRITICAL"
	SeverityHigh     Severity = "HIGH"
	SeverityMedium   Severity = "MEDIUM"
	SeverityLow      Severity = "LOW"
)

var AllSeverity = []Severity{
	SeverityCritical,
	SeverityHigh,
	SeverityMedium,
	SeverityLow,
}

func (e Severity) IsValid() bool {
	switch e {
	case SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow:
		return true
	}
	return false
}

func (e Severity) String() string {
	return string(e)
}

func (e *Severity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Severity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Severity", str)
	}
	return nil
}

func (e Severity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
